apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloweb
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
      tier: web
  template:
    metadata:
      labels:
        app: hello
        tier: web
    spec:
      containers:
      - name: hello-app
        image: europe-docker.pkg.dev/alans-gcp-project/helloweb-repo/hello-app:v3.4.0
        ports:
        - containerPort: 8080
